# Synteny of the RBH hits

For every reciprocal best hit from `1_run_bidirectional_blast.py`, checks whether other hits of the same
reference cluster (SCO or VNZ) in the same genome lie within `N_NEIGHBOURS` genes on either side.

Gene order is taken from the protein `.faa` files (proteins are in genome order), via `shared/synteny.py`.
Positions run continuously through each file, so on draft genomes two genes at the ends of different contigs
can count as neighbours.

In [12]:
import sys
from pathlib import Path

import pandas as pd

PROJECT_DIR = Path("/vol/local/calarass/Projects/ara_comp_genomics")
sys.path.insert(0, str(PROJECT_DIR / "shared"))
from synteny import find_neighbours, get_gene_iterator

RBH_HITS = PROJECT_DIR / "RBH" / "results" / "diamond_reverseBLAST_streptomycetae" / "reciprocal" / "reciprocal_hits.tsv"
FAA_DIR = Path("/vol/local/calarass/Projects/lipid_genomics/faa_files")
N_NEIGHBOURS = 5

## 1. Load the RBH hits

In [13]:
rbh_hits = pd.read_csv(RBH_HITS, sep="\t")
rbh_hits["locus_tag"] = rbh_hits.sseqid.str.split("|").str[1]

print(f"{len(rbh_hits)} hits, {rbh_hits.genome.nunique()} genomes")
rbh_hits.groupby(["ref_group", "qseqid"]).genome.nunique()

885 hits, 157 genomes

ref_group  qseqid
SCO        SCO2401           130
           SCO2402           130
           SCO2403           129
           SCO2407            95
           SCO2439           125
           SCO2440           132
VNZ        vnz_33170-lacI     43
           vnz_33175-araB     32
           vnz_33180-araA     32
           vnz_33185-araD     24
Name: genome, dtype: int64

## 2. Match genomes to their `.faa` files

By the genome name in the first header, not the file name (file names are not consistent, e.g. no `_protein` suffix).

In [14]:
def genome_of_faa(faa_file: Path) -> str:
    """Genome name from the first header, brackets dropped to match the genome column of reciprocal_hits.tsv."""
    with open(faa_file) as f:
        header = f.readline()
    return header.lstrip(">").split("|")[0].replace("[", "").replace("]", "")


FAA_FILES = {genome_of_faa(path): path for path in sorted(FAA_DIR.glob("*.faa"))}

missing = sorted(set(rbh_hits.genome) - set(FAA_FILES))
if missing:
    print("WARNING: no .faa file for:", missing)

## 3. Neighbouring hits

Per reference group (SCO / VNZ) and genome: for each hit, which other hits of the same group are among its
`N_NEIGHBOURS` genes to the left and right.

In [15]:
rows = []
for genome, genome_hits in rbh_hits.groupby("genome"):
    gene_positions = get_gene_iterator(FAA_FILES[genome])
    for ref_group, group_hits in genome_hits.groupby("ref_group"):
        hit_genes = dict(zip(group_hits.locus_tag, group_hits.qseqid))
        for hit in group_hits.itertuples():
            neighbours = find_neighbours(hit.locus_tag, gene_positions, N_NEIGHBOURS)
            neighbour_hits = [f"{hit_genes[n]}:{n}" for n in neighbours if n in hit_genes]
            rows.append({
                "ref_group": ref_group,
                "genome": genome,
                "qseqid": hit.qseqid,
                "locus_tag": hit.locus_tag,
                "neighbour_hits": ", ".join(neighbour_hits),
                "has_neighbours": "yes" if neighbour_hits else "no",
            })

synteny_table = pd.DataFrame(rows).sort_values(["ref_group", "genome", "qseqid"]).reset_index(drop=True)
synteny_table

,ref_group,genome,qseqid,locus_tag,neighbour_hits,has_neighbours
0,SCO,Actinacidiphila_glaucinigra,SCO2401,OIE69_RS26950,"SCO2403:OIE69_RS26940, SCO2402:OIE69_RS26945",yes
1,SCO,Actinacidiphila_glaucinigra,SCO2402,OIE69_RS26945,"SCO2407:OIE69_RS26920, SCO2403:OIE69_RS26940, ...",yes
2,SCO,Actinacidiphila_glaucinigra,SCO2403,OIE69_RS26940,"SCO2407:OIE69_RS26920, SCO2402:OIE69_RS26945, ...",yes
3,SCO,Actinacidiphila_glaucinigra,SCO2407,OIE69_RS26920,"SCO2403:OIE69_RS26940, SCO2402:OIE69_RS26945",yes
4,SCO,Actinacidiphila_glaucinigra,SCO2439,OIE69_RS26865,SCO2440:OIE69_RS26860,yes
...,...,...,...,...,...,...
880,VNZ,Streptomyces_venezuelae_ATCC_10712,vnz_33185-araD,DEJ43_RS33670,"vnz_33170-lacI:DEJ43_RS33655, vnz_33175-araB:D...",yes
881,VNZ,Streptomyces_vietnamensis,vnz_33170-lacI,SVTN_RS36800,"vnz_33175-araB:SVTN_RS36805, vnz_33180-araA:SV...",yes
882,VNZ,Streptomyces_vietnamensis,vnz_33175-araB,SVTN_RS36805,"vnz_33170-lacI:SVTN_RS36800, vnz_33180-araA:SV...",yes
883,VNZ,Streptomyces_vietnamensis,vnz_33180-araA,SVTN_RS36810,"vnz_33170-lacI:SVTN_RS36800, vnz_33175-araB:SV...",yes
884,VNZ,Streptomyces_vietnamensis,vnz_33185-araD,SVTN_RS36815,"vnz_33170-lacI:SVTN_RS36800, vnz_33175-araB:SV...",yes

In [16]:
synteny_table.loc[synteny_table.has_neighbours == "no"].groupby(["ref_group", "qseqid"]).genome.nunique().sort_values(ascending=False).head(10)

ref_group  qseqid
VNZ        vnz_33170-lacI    22
SCO        SCO2439            6
           SCO2407            6
           SCO2402            2
           SCO2440            2
VNZ        vnz_33175-araB     1
           vnz_33185-araD     1
Name: genome, dtype: int64

### 3b. SCO2401 / SCO2402 / SCO2403 trio

In *S. coelicolor* SCO2401-SCO2403 sit next to each other. Per genome and query gene: is the gene directly to the
left or right (`TRIO_WINDOW` genes) of the hit itself a hit of another trio gene?

`trio_summary` then gives one row per genome: `trio` = all three genes in one adjacent block, `pair` = at most two
of them adjacent, `none` = hits present but not adjacent. Tandem copies of the same gene next to each other do not count.

In [17]:
TRIO = ["SCO2401", "SCO2402", "SCO2403"]
TRIO_WINDOW = 1  # direct left/right neighbour only

trio_hits = rbh_hits[rbh_hits.qseqid.isin(TRIO)]

rows = []
for genome, genome_hits in trio_hits.groupby("genome"):
    gene_positions = get_gene_iterator(FAA_FILES[genome])
    hit_genes = dict(zip(genome_hits.locus_tag, genome_hits.qseqid))
    for hit in genome_hits.itertuples():
        neighbours = find_neighbours(hit.locus_tag, gene_positions, TRIO_WINDOW)
        # another trio gene next to it - a neighbouring copy of the same gene is not counted
        trio_neighbours = [f"{hit_genes[n]}:{n}" for n in neighbours if n in hit_genes and hit_genes[n] != hit.qseqid]
        rows.append({
            "genome": genome,
            "qseqid": hit.qseqid,
            "locus_tag": hit.locus_tag,
            "position": gene_positions[hit.locus_tag],
            "trio_neighbours": ", ".join(trio_neighbours),
            "has_any_trio_neighbour": "yes" if trio_neighbours else "no",
        })

trio_table = pd.DataFrame(rows).sort_values(["genome", "position"]).reset_index(drop=True)
trio_table

,genome,qseqid,locus_tag,position,trio_neighbours,has_any_trio_neighbour
0,Actinacidiphila_glaucinigra,SCO2403,OIE69_RS26940,5191,SCO2402:OIE69_RS26945,yes
1,Actinacidiphila_glaucinigra,SCO2402,OIE69_RS26945,5192,"SCO2403:OIE69_RS26940, SCO2401:OIE69_RS26950",yes
2,Actinacidiphila_glaucinigra,SCO2401,OIE69_RS26950,5193,SCO2402:OIE69_RS26945,yes
3,Kitasatospora_papulosa,SCO2403,OG362_RS22095,4297,SCO2402:OG362_RS22100,yes
4,Kitasatospora_papulosa,SCO2402,OG362_RS22100,4298,"SCO2403:OG362_RS22095, SCO2401:OG362_RS22105",yes
...,...,...,...,...,...,...
386,Streptomyces_yatensis,SCO2402,J8403_RS29520,5748,"SCO2403:J8403_RS29515, SCO2401:J8403_RS29525",yes
387,Streptomyces_yatensis,SCO2401,J8403_RS29525,5749,SCO2402:J8403_RS29520,yes
388,Streptomyces_zaomyceticus,SCO2403,OG567_RS33905,6619,,no
389,Streptomyces_zaomyceticus,SCO2402,OG567_RS34790,6793,SCO2401:OG567_RS34795,yes
390,Streptomyces_zaomyceticus,SCO2401,OG567_RS34795,6794,SCO2402:OG567_RS34790,yes

In [19]:
trio_table.groupby("genome").agg(
    n_hits=("qseqid", "size"),
    genes=("qseqid", ", ".join),
    locus_tags=("locus_tag", ", ".join),
    positions=("position", list),
    with_trio_neighbour=("has_any_trio_neighbour", lambda s: (s == "yes").sum()),
).head(20)

,n_hits,genes,locus_tags,positions,with_trio_neighbour
genome,,,,,
Actinacidiphila_glaucinigra,3,"SCO2403, SCO2402, SCO2401","OIE69_RS26940, OIE69_RS26945, OIE69_RS26950","[5191, 5192, 5193]",3
Kitasatospora_papulosa,3,"SCO2403, SCO2402, SCO2401","OG362_RS22095, OG362_RS22100, OG362_RS22105","[4297, 4298, 4299]",3
Peterkaempfera_sp._SMS_1(5)a,2,"SCO2403, SCO2402","AB0761_RS30805, AB0761_RS30810","[5790, 5791]",2
Streptomyces_achromogenes,3,"SCO2401, SCO2402, SCO2403","OG350_RS12710, OG350_RS12715, OG350_RS12720","[2465, 2466, 2467]",3
Streptomyces_akebiae,3,"SCO2403, SCO2402, SCO2401","K1J60_RS31245, K1J60_RS31250, K1J60_RS31255","[6065, 6066, 6067]",3
Streptomyces_albidocamelliae,3,"SCO2401, SCO2402, SCO2403","N8I86_RS13315, N8I86_RS13320, N8I86_RS13325","[2521, 2522, 2523]",3
Streptomyces_alboniger,3,"SCO2403, SCO2402, SCO2401","CP975_RS30020, CP975_RS30025, CP975_RS30030","[5824, 5825, 5826]",3
Streptomyces_alfalfae,3,"SCO2403, SCO2402, SCO2401","H9W91_RS31130, H9W91_RS31135, H9W91_RS31140","[6051, 6052, 6053]",3
Streptomyces_althioticus,3,"SCO2403, SCO2402, SCO2401","OG872_RS23315, OG872_RS23320, OG872_RS23325","[4520, 4521, 4522]",3
Streptomyces_ambofaciens_ATCC_23877,3,"SCO2401, SCO2402, SCO2403","SAM23877_RS11640, SAM23877_RS11645, SAM23877_R...","[2297, 2298, 2299]",3
Streptomyces_anthocyanicus,3,"SCO2403, SCO2402, SCO2401","OIE72_RS26110, OIE72_RS26115, OIE72_RS26120","[5063, 5064, 5065]",3
Streptomyces_antimycoticus,3,"SCO2401, SCO2402, SCO2403","OG751_RS16860, OG751_RS16865, OG751_RS16870","[3126, 3127, 3128]",3
Streptomyces_aquilus,3,"SCO2401, SCO2402, SCO2403","EJC51_RS15950, EJC51_RS15955, EJC51_RS15960","[3085, 3086, 3087]",3
Streptomyces_argyrophylli,3,"SCO2403, SCO2402, SCO2401","HKX69_RS23545, HKX69_RS23550, HKX69_RS23555","[4590, 4591, 4592]",3
Streptomyces_aurantiacus,3,"SCO2403, SCO2402, SCO2401","IGS71_RS28100, IGS71_RS28105, IGS71_RS28110","[5492, 5493, 5494]",3
Streptomyces_avermitilis_MA-4680_=_NBRC_14893,3,"SCO2403, SCO2402, SCO2401","SAVERM_RS29755, SAVERM_RS29760, SAVERM_RS29765","[5798, 5799, 5800]",3
Streptomyces_bathyalis,3,"SCO2403, SCO2402, SCO2401","G4Z16_RS24420, G4Z16_RS24425, G4Z16_RS24430","[4778, 4779, 4780]",3
Streptomyces_bobili,3,"SCO2403, SCO2402, SCO2401","OHT53_RS28125, OHT53_RS28130, OHT53_RS28135","[5399, 5400, 5401]",3
Streptomyces_boninensis,3,"SCO2401, SCO2402, SCO2403","ACNNMR_RS23270, ACNNMR_RS23275, ACNNMR_RS23280","[4529, 4530, 4531]",3
Streptomyces_broussonetiae,3,"SCO2401, SCO2402, SCO2403","GQF42_RS15010, GQF42_RS15015, GQF42_RS15020","[2870, 2871, 2872]",3

In [20]:
def adjacent_blocks(genome_hits: pd.DataFrame) -> list[set[str]]:
    """Split a genome's trio hits (sorted by position) into runs of genes at most TRIO_WINDOW apart;
    return the set of trio genes in each run."""
    blocks = []
    previous = None
    for hit in genome_hits.itertuples():
        if previous is None or hit.position - previous > TRIO_WINDOW:
            blocks.append(set())
        blocks[-1].add(hit.qseqid)
        previous = hit.position
    return blocks


rows = []
for genome, genome_hits in trio_table.groupby("genome"):
    largest = max(adjacent_blocks(genome_hits), key=len)
    rows.append({
        "genome": genome,
        "trio_genes_found": ", ".join(sorted(genome_hits.qseqid.unique())),
        "largest_block": ", ".join(sorted(largest)),
        "neighbourhood": {3: "trio", 2: "pair"}.get(len(largest), "none"),
    })

trio_summary = pd.DataFrame(rows)
print(f"{len(trio_summary)} genomes with at least one SCO2401-2403 hit")
trio_summary.groupby(["trio_genes_found", "neighbourhood"]).size()

132 genomes with at least one SCO2401-2403 hit

trio_genes_found           neighbourhood
SCO2401                    none               2
SCO2401, SCO2402, SCO2403  pair               1
                           trio             127
SCO2402                    none               1
SCO2402, SCO2403           pair               1
dtype: int64

In [21]:
# genomes where the three genes are not all in one block
trio_summary[trio_summary.neighbourhood != "trio"].sort_values(["neighbourhood", "genome"])

,genome,trio_genes_found,largest_block,neighbourhood
53,Streptomyces_gobiensis,SCO2402,SCO2402,none
121,Streptomyces_venezuelae,SCO2401,SCO2401,none
122,Streptomyces_venezuelae_ATCC_10712,SCO2401,SCO2401,none
2,Peterkaempfera_sp._SMS_1(5)a,"SCO2402, SCO2403","SCO2402, SCO2403",pair
131,Streptomyces_zaomyceticus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402",pair

In [22]:
trio_summary.head(29)

,genome,trio_genes_found,largest_block,neighbourhood
0,Actinacidiphila_glaucinigra,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
1,Kitasatospora_papulosa,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
2,Peterkaempfera_sp._SMS_1(5)a,"SCO2402, SCO2403","SCO2402, SCO2403",pair
3,Streptomyces_achromogenes,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
4,Streptomyces_akebiae,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
5,Streptomyces_albidocamelliae,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
6,Streptomyces_alboniger,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
7,Streptomyces_alfalfae,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
8,Streptomyces_althioticus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
9,Streptomyces_ambofaciens_ATCC_23877,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
10,Streptomyces_anthocyanicus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
11,Streptomyces_antimycoticus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
12,Streptomyces_aquilus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
13,Streptomyces_argyrophylli,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
14,Streptomyces_aurantiacus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
15,Streptomyces_avermitilis_MA-4680_=_NBRC_14893,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
16,Streptomyces_bathyalis,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
17,Streptomyces_bobili,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
18,Streptomyces_boninensis,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
19,Streptomyces_broussonetiae,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
20,Streptomyces_cadmiisoli,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
21,Streptomyces_calvus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
22,Streptomyces_camelliae,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
23,Streptomyces_canus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
24,Streptomyces_carpaticus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
25,Streptomyces_cathayae,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
26,Streptomyces_changanensis,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
27,Streptomyces_chartreusis,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio
28,Streptomyces_chromofuscus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio

In [23]:
trio_summary[trio_summary.genome.str.contains("griseorubiginosus")]

,genome,trio_genes_found,largest_block,neighbourhood
58,Streptomyces_griseorubiginosus,"SCO2401, SCO2402, SCO2403","SCO2401, SCO2402, SCO2403",trio

## 4. Investigate hits without neighbours

`isolated_hits`: for every hit with `has_neighbours == "no"`, the nearest other hit of the same reference group
in that genome and how many genes away it is (NaN = the only hit of its group in that genome).

`show_neighbourhood` lists the `WINDOW` genes on each side of a hit with their full description from the `.faa`
header; `rbh_hit` marks genes that are themselves RBH hits (of either group).

In [41]:
WINDOW = 10


def read_descriptions(faa_file: Path) -> dict[str, str]:
    """Return {locus_tag: description} from the '>Genome|LOCUS_TAG|description|accession' headers."""
    descriptions = {}
    with open(faa_file) as f:
        for line in f:
            if line.startswith(">"):
                fields = line.split("|")
                descriptions[fields[1]] = fields[2]
    return descriptions


def show_neighbourhood(genome: str, locus_tag: str, window: int = WINDOW) -> pd.DataFrame:
    """The window genes on each side of locus_tag, in genome order, with descriptions and RBH hits marked."""
    gene_positions = get_gene_iterator(FAA_FILES[genome])
    descriptions = read_descriptions(FAA_FILES[genome])
    genome_hits = synteny_table[synteny_table.genome == genome]
    hit_genes = dict(zip(genome_hits.locus_tag, genome_hits.qseqid))

    genes = sorted(find_neighbours(locus_tag, gene_positions, window) + [locus_tag], key=gene_positions.get)
    return pd.DataFrame({
        "offset": [gene_positions[g] - gene_positions[locus_tag] for g in genes],
        "locus_tag": genes,
        "description": [descriptions[g] for g in genes],
        "rbh_hit": [hit_genes.get(g, "") for g in genes],
    })


rows = []
for genome, genome_isolated in synteny_table[synteny_table.has_neighbours == "no"].groupby("genome"):
    gene_positions = get_gene_iterator(FAA_FILES[genome])
    genome_hits = synteny_table[synteny_table.genome == genome]
    for hit in genome_isolated.itertuples():
        others = genome_hits[(genome_hits.ref_group == hit.ref_group) & (genome_hits.locus_tag != hit.locus_tag)]
        distances = {f"{o.qseqid}:{o.locus_tag}": abs(gene_positions[o.locus_tag] - gene_positions[hit.locus_tag])
                     for o in others.itertuples()}
        nearest = min(distances, key=distances.get) if distances else None
        rows.append({
            "ref_group": hit.ref_group,
            "genome": genome,
            "qseqid": hit.qseqid,
            "locus_tag": hit.locus_tag,
            "other_group_hits": len(others),
            "nearest_hit": nearest,
            "genes_away": distances.get(nearest),
        })

isolated_hits = pd.DataFrame(rows).sort_values(["ref_group", "qseqid", "genes_away"]).reset_index(drop=True)
isolated_hits.groupby(["ref_group", "qseqid"]).size()

ref_group  qseqid
SCO        SCO2402            2
           SCO2407           23
           SCO2439            5
           SCO2440            2
VNZ        vnz_33170-lacI    25
           vnz_33175-araB     2
           vnz_33180-araA     1
           vnz_33185-araD     2
dtype: int64

### SCO2407

In [42]:
sco2407 = isolated_hits[isolated_hits.qseqid.isin(["SCO2407"])]
sco2407

,ref_group,genome,qseqid,locus_tag,other_group_hits,nearest_hit,genes_away
2,SCO,Streptomyces_seoulensis,SCO2407,D0Z67_RS08555,5,SCO2401:D0Z67_RS08585,6.0
3,SCO,Streptomyces_dengpaensis,SCO2407,C4B68_RS27745,5,SCO2401:C4B68_RS27695,8.0
4,SCO,Streptomyces_cynarae,SCO2407,N8I84_RS13275,5,SCO2401:N8I84_RS13325,10.0
5,SCO,Streptomyces_longhuiensis,SCO2407,LGI35_RS16010,5,SCO2401:LGI35_RS16060,10.0
6,SCO,Streptomyces_bobili,SCO2407,OHT53_RS28210,5,SCO2401:OHT53_RS28135,14.0
7,SCO,Streptomyces_phaeoluteigriseus,SCO2407,NFX46_RS32755,5,SCO2401:NFX46_RS32835,15.0
8,SCO,Streptomyces_ferrugineus,SCO2407,IM697_RS09605,5,SCO2401:IM697_RS09525,16.0
9,SCO,Streptomyces_collinus,SCO2407,RFN52_RS12085,5,SCO2401:RFN52_RS12180,19.0
10,SCO,Streptomyces_canus,SCO2407,OHT68_RS32760,5,SCO2401:OHT68_RS32655,21.0
11,SCO,Streptomyces_cyaneochromogenes,SCO2407,EJ357_RS14015,5,SCO2401:EJ357_RS14170,28.0
12,SCO,Streptomyces_vilmorinianum,SCO2407,FDM97_RS19630,5,SCO2439:FDM97_RS20105,90.0
13,SCO,Streptomyces_phytohabitans,SCO2407,ABXR15_RS17595,5,SCO2401:ABXR15_RS20350,534.0
14,SCO,Streptomyces_poriferorum,SCO2407,P8A21_RS38345,5,SCO2401:P8A21_RS34285,795.0
15,SCO,Streptomyces_paludis,SCO2407,DVK44_RS35315,4,SCO2440:DVK44_RS30615,922.0
16,SCO,Streptomyces_xiamenensis,SCO2407,SXIM_RS01350,5,SCO2401:SXIM_RS06610,1021.0
17,SCO,Streptomyces_boninensis,SCO2407,ACNNMR_RS34500,5,SCO2403:ACNNMR_RS23280,2188.0
18,SCO,Streptomyces_bathyalis,SCO2407,G4Z16_RS02255,5,SCO2440:G4Z16_RS24380,4331.0
19,SCO,Streptomyces_kanamyceticus,SCO2407,CP970_RS30000,5,SCO2403:CP970_RS06475,4574.0
20,SCO,Streptomyces_hebeiensis,SCO2407,ACU6P3_RS00270,5,SCO2403:ACU6P3_RS29140,5509.0
21,SCO,Streptomyces_griseofuscus,SCO2407,HEP81_RS26590,0,None,NaN
22,SCO,Streptomyces_murinus,SCO2407,GO605_RS29930,0,None,NaN
23,SCO,Streptomyces_nodosus,SCO2407,CP978_RS11535,0,None,NaN
24,SCO,Streptomyces_tubercidicus,SCO2407,STRTU_RS24690,0,None,NaN

In [43]:
for hit in sco2407.itertuples():
    print(f"{hit.genome}  {hit.locus_tag}  (nearest: {hit.nearest_hit}, {hit.genes_away} genes away)")
    display(show_neighbourhood(hit.genome, hit.locus_tag))

Streptomyces_seoulensis  D0Z67_RS08555  (nearest: SCO2401:D0Z67_RS08585, 6.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,D0Z67_RS08505,GNAT family N-acetyltransferase,
1,-9,D0Z67_RS08510,serine hydrolase domain-containing protein,
2,-8,D0Z67_RS08515,pirin family protein,
3,-7,D0Z67_RS08520,PucR family transcriptional regulator,
4,-6,D0Z67_RS08525,ACP S-malonyltransferase,
5,-5,D0Z67_RS08530,ketoacyl-ACP synthase III,
6,-4,D0Z67_RS08535,acyl carrier protein,
7,-3,D0Z67_RS08540,beta-ketoacyl-ACP synthase II,
8,-2,D0Z67_RS08545,DUF3145 domain-containing protein,
9,-1,D0Z67_RS08550,SGNH/GDSL hydrolase family protein,
10,0,D0Z67_RS08555,aldose epimerase family protein,SCO2407
11,1,D0Z67_RS08560,EI24 domain-containing protein,
12,2,D0Z67_RS08565,MarR family winged helix-turn-helix transcript...,
13,3,D0Z67_RS08570,NADP-dependent oxidoreductase,
14,4,D0Z67_RS08575,EstA family serine hydrolase,
15,5,D0Z67_RS08580,SCO2400 family protein,
16,6,D0Z67_RS08585,mandelate racemase/muconate lactonizing enzyme...,SCO2401
17,7,D0Z67_RS08590,zinc-dependent alcohol dehydrogenase,SCO2402
18,8,D0Z67_RS08595,hypothetical protein,SCO2403
19,9,D0Z67_RS08600,multiple monosaccharide ABC transporter substr...,
20,10,D0Z67_RS08605,multiple monosaccharide ABC transporter ATP-bi...,

Streptomyces_dengpaensis  C4B68_RS27745  (nearest: SCO2401:C4B68_RS27695, 8.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,C4B68_RS27685,hypothetical protein,SCO2403
1,-9,C4B68_RS27690,zinc-dependent alcohol dehydrogenase,SCO2402
2,-8,C4B68_RS27695,mandelate racemase/muconate lactonizing enzyme...,SCO2401
3,-7,C4B68_RS42115,SCO2400 family protein,
4,-6,C4B68_RS27715,hypothetical protein,
5,-5,C4B68_RS27720,M14 family zinc carboxypeptidase,
6,-4,C4B68_RS27725,NADP-dependent oxidoreductase,
7,-3,C4B68_RS27730,MarR family winged helix-turn-helix transcript...,
8,-2,C4B68_RS27735,EI24 domain-containing protein,
9,-1,C4B68_RS27740,pyroglutamyl peptidase,
10,0,C4B68_RS27745,aldose epimerase family protein,SCO2407
11,1,C4B68_RS27750,SGNH/GDSL hydrolase family protein,
12,2,C4B68_RS27755,DUF3145 domain-containing protein,
13,3,C4B68_RS27760,beta-ketoacyl-ACP synthase II,
14,4,C4B68_RS27765,acyl carrier protein,
15,5,C4B68_RS27770,ketoacyl-ACP synthase III,
16,6,C4B68_RS27775,ACP S-malonyltransferase,
17,7,C4B68_RS27780,PucR family transcriptional regulator,
18,8,C4B68_RS27785,pirin family protein,
19,9,C4B68_RS27790,serine hydrolase domain-containing protein,
20,10,C4B68_RS27795,GNAT family N-acetyltransferase,

Streptomyces_cynarae  N8I84_RS13275  (nearest: SCO2401:N8I84_RS13325, 10.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,N8I84_RS13225,GNAT family N-acetyltransferase,
1,-9,N8I84_RS13230,serine hydrolase domain-containing protein,
2,-8,N8I84_RS13235,pirin family protein,
3,-7,N8I84_RS13240,fatty acid biosynthesis transcriptional regula...,
4,-6,N8I84_RS13245,ACP S-malonyltransferase,
5,-5,N8I84_RS13250,ketoacyl-ACP synthase III,
6,-4,N8I84_RS13255,acyl carrier protein,
7,-3,N8I84_RS13260,beta-ketoacyl-ACP synthase II,
8,-2,N8I84_RS13265,DUF3145 domain-containing protein,
9,-1,N8I84_RS13270,SGNH/GDSL hydrolase family protein,
10,0,N8I84_RS13275,aldose epimerase family protein,SCO2407
11,1,N8I84_RS13280,EI24 domain-containing protein,
12,2,N8I84_RS13285,NADP-dependent oxidoreductase,
13,3,N8I84_RS13290,MarR family winged helix-turn-helix transcript...,
14,4,N8I84_RS13295,"galactofuranose ABC transporter, permease prot...",
15,5,N8I84_RS13300,ABC transporter permease,
16,6,N8I84_RS13305,sugar ABC transporter ATP-binding protein,
17,7,N8I84_RS13310,ABC transporter substrate-binding protein,
18,8,N8I84_RS13315,LacI family DNA-binding transcriptional regulator,vnz_33170-lacI
19,9,N8I84_RS13320,SCO2400 family protein,
20,10,N8I84_RS13325,mandelate racemase/muconate lactonizing enzyme...,SCO2401

Streptomyces_longhuiensis  LGI35_RS16010  (nearest: SCO2401:LGI35_RS16060, 10.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,LGI35_RS15960,MerR family transcriptional regulator,
1,-9,LGI35_RS15965,serine hydrolase domain-containing protein,
2,-8,LGI35_RS15970,pirin family protein,
3,-7,LGI35_RS15975,PucR family transcriptional regulator,
4,-6,LGI35_RS15980,ACP S-malonyltransferase,
5,-5,LGI35_RS15985,ketoacyl-ACP synthase III,
6,-4,LGI35_RS15990,acyl carrier protein,
7,-3,LGI35_RS15995,beta-ketoacyl-[acyl-carrier-protein] synthase ...,
8,-2,LGI35_RS16000,DUF3145 domain-containing protein,
9,-1,LGI35_RS16005,SGNH/GDSL hydrolase family protein,
10,0,LGI35_RS16010,aldose epimerase family protein,SCO2407
11,1,LGI35_RS16015,beta-glucosidase,
12,2,LGI35_RS16020,TetR/AcrR family transcriptional regulator,
13,3,LGI35_RS16025,YrdB family protein,
14,4,LGI35_RS16030,NAD(P)-dependent oxidoreductase,
15,5,LGI35_RS16035,EI24 domain-containing protein,
16,6,LGI35_RS16040,organic hydroperoxide resistance protein,
17,7,LGI35_RS16045,NADP-dependent oxidoreductase,
18,8,LGI35_RS16050,MarR family winged helix-turn-helix transcript...,
19,9,LGI35_RS16055,SCO2400 family protein,
20,10,LGI35_RS16060,mandelate racemase/muconate lactonizing enzyme...,SCO2401

Streptomyces_bobili  OHT53_RS28210  (nearest: SCO2401:OHT53_RS28135, 14.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,OHT53_RS28160,sugar ABC transporter ATP-binding protein,
1,-9,OHT53_RS28165,ABC transporter permease,
2,-8,OHT53_RS28170,"galactofuranose ABC transporter, permease prot...",
3,-7,OHT53_RS28175,MarR family winged helix-turn-helix transcript...,
4,-6,OHT53_RS28180,NADP-dependent oxidoreductase,
5,-5,OHT53_RS28185,serine hydrolase domain-containing protein,
6,-4,OHT53_RS28190,EI24 domain-containing protein,
7,-3,OHT53_RS28195,pyroglutamyl peptidase,
8,-2,OHT53_RS28200,TetR/AcrR family transcriptional regulator,
9,-1,OHT53_RS28205,beta-glucosidase family protein,
10,0,OHT53_RS28210,aldose epimerase family protein,SCO2407
11,1,OHT53_RS28215,SGNH/GDSL hydrolase family protein,
12,2,OHT53_RS28220,DUF3145 domain-containing protein,
13,3,OHT53_RS28225,beta-ketoacyl-ACP synthase II,
14,4,OHT53_RS28230,acyl carrier protein,
15,5,OHT53_RS28235,ketoacyl-ACP synthase III,
16,6,OHT53_RS28240,ACP S-malonyltransferase,
17,7,OHT53_RS28245,PucR family transcriptional regulator,
18,8,OHT53_RS28250,pirin family protein,
19,9,OHT53_RS28255,serine/threonine-protein kinase,
20,10,OHT53_RS28260,serine hydrolase domain-containing protein,

Streptomyces_phaeoluteigriseus  NFX46_RS32755  (nearest: SCO2401:NFX46_RS32835, 15.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,NFX46_RS32705,serine hydrolase domain-containing protein,
1,-9,NFX46_RS32710,protein kinase domain-containing protein,
2,-8,NFX46_RS32715,pirin family protein,
3,-7,NFX46_RS32720,PucR family transcriptional regulator,
4,-6,NFX46_RS32725,ACP S-malonyltransferase,
5,-5,NFX46_RS32730,ketoacyl-ACP synthase III,
6,-4,NFX46_RS32735,acyl carrier protein,
7,-3,NFX46_RS32740,beta-ketoacyl-ACP synthase II,
8,-2,NFX46_RS32745,DUF3145 domain-containing protein,
9,-1,NFX46_RS32750,SGNH/GDSL hydrolase family protein,
10,0,NFX46_RS32755,aldose epimerase family protein,SCO2407
11,1,NFX46_RS32760,beta-glucosidase H,
12,2,NFX46_RS32765,TetR/AcrR family transcriptional regulator,
13,3,NFX46_RS32770,pyroglutamyl peptidase,
14,4,NFX46_RS32775,EI24 domain-containing protein,
15,5,NFX46_RS32780,M14 family zinc carboxypeptidase,
16,6,NFX46_RS32785,serine hydrolase domain-containing protein,
17,7,NFX46_RS32790,NADP-dependent oxidoreductase,
18,8,NFX46_RS32795,MarR family winged helix-turn-helix transcript...,
19,9,NFX46_RS32800,"galactofuranose ABC transporter, permease prot...",
20,10,NFX46_RS32805,ABC transporter permease,

Streptomyces_ferrugineus  IM697_RS09605  (nearest: SCO2401:IM697_RS09525, 16.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,IM697_RS09555,"galactofuranose ABC transporter, permease prot...",
1,-9,IM697_RS09560,MarR family winged helix-turn-helix transcript...,
2,-8,IM697_RS09565,NADP-dependent oxidoreductase,
3,-7,IM697_RS09570,organic hydroperoxide resistance protein,
4,-6,IM697_RS09575,hypothetical protein,
5,-5,IM697_RS09580,M14 family zinc carboxypeptidase,
6,-4,IM697_RS09585,hypothetical protein,
7,-3,IM697_RS09590,EI24 domain-containing protein,
8,-2,IM697_RS09595,pyroglutamyl peptidase,
9,-1,IM697_RS09600,glycoside hydrolase family 3 protein,
10,0,IM697_RS09605,aldose epimerase family protein,SCO2407
11,1,IM697_RS09610,SGNH/GDSL hydrolase family protein,
12,2,IM697_RS09615,DUF3145 domain-containing protein,
13,3,IM697_RS09620,beta-ketoacyl-[acyl-carrier-protein] synthase ...,
14,4,IM697_RS09625,acyl carrier protein,
15,5,IM697_RS09630,ketoacyl-ACP synthase III,
16,6,IM697_RS09635,ACP S-malonyltransferase,
17,7,IM697_RS09640,fatty acid biosynthesis transcriptional regula...,
18,8,IM697_RS09645,pirin family protein,
19,9,IM697_RS09650,hypothetical protein,
20,10,IM697_RS09655,serine hydrolase domain-containing protein,

Streptomyces_collinus  RFN52_RS12085  (nearest: SCO2401:RFN52_RS12180, 19.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,RFN52_RS12035,GNAT family N-acetyltransferase,
1,-9,RFN52_RS12040,serine hydrolase domain-containing protein,
2,-8,RFN52_RS12045,pirin family protein,
3,-7,RFN52_RS12050,fatty acid biosynthesis transcriptional regula...,
4,-6,RFN52_RS12055,ACP S-malonyltransferase,
5,-5,RFN52_RS12060,ketoacyl-ACP synthase III,
6,-4,RFN52_RS12065,acyl carrier protein,
7,-3,RFN52_RS12070,beta-ketoacyl-ACP synthase II,
8,-2,RFN52_RS12075,DUF3145 domain-containing protein,
9,-1,RFN52_RS12080,SGNH/GDSL hydrolase family protein,
10,0,RFN52_RS12085,aldose epimerase family protein,SCO2407
11,1,RFN52_RS12090,beta-glucosidase family protein,
12,2,RFN52_RS12095,TetR family transcriptional regulator C-termin...,
13,3,RFN52_RS12100,RidA family protein,
14,4,RFN52_RS12105,LysR family transcriptional regulator,
15,5,RFN52_RS12110,pyroglutamyl peptidase,
16,6,RFN52_RS12115,EI24 domain-containing protein,
17,7,RFN52_RS12120,M14 family zinc carboxypeptidase,
18,8,RFN52_RS12125,serine hydrolase domain-containing protein,
19,9,RFN52_RS12130,organic hydroperoxide resistance protein,
20,10,RFN52_RS12135,NADP-dependent oxidoreductase,

Streptomyces_canus  OHT68_RS32760  (nearest: SCO2401:OHT68_RS32655, 21.0 genes away)

    offset      locus_tag                                 description  rbh_hit
0      -10  OHT68_RS32710            M14 family zinc carboxypeptidase
1       -9  OHT68_RS32715                        hypothetical protein
2       -8  OHT68_RS32720              EI24 domain-containing protein
3       -7  OHT68_RS32725             GNAT family N-acetyltransferase
4       -6  OHT68_RS32730                      pyroglutamyl peptidase
5       -5  OHT68_RS32735       LysR family transcriptional regulator
6       -4  OHT68_RS32740                         RidA family protein
7       -3  OHT68_RS32745                         YrdB family protein
8       -2  OHT68_RS32750  TetR/AcrR family transcriptional regulator
9       -1  OHT68_RS32755                            beta-glucosidase
10       0  OHT68_RS32760             aldose epimerase family protein  SCO2407
11       1  OHT68_RS32765          SGNH/GDSL hydrolase family protein
12       2  OHT68_RS32770           DUF3145 domain-containing protein
13       3  OHT68_RS32775               beta-ketoacyl-ACP synthase II
14       4  OHT68_RS32780                        acyl carrier protein
15       5  OHT68_RS32785                   ketoacyl-ACP synthase III
16       6  OHT68_RS32790                    ACP S-malonyltransferase
17       7  OHT68_RS32795       PucR family transcriptional regulator
18       8  OHT68_RS32800                        pirin family protein
19       9  OHT68_RS32805  serine hydrolase domain-containing protein
20      10  OHT68_RS32810       MerR family transcriptional regulator

Streptomyces_cyaneochromogenes  EJ357_RS14015  (nearest: SCO2401:EJ357_RS14170, 28.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,EJ357_RS13965,serine hydrolase domain-containing protein,
1,-9,EJ357_RS13970,MMPL family transporter,
2,-8,EJ357_RS13975,pirin family protein,
3,-7,EJ357_RS13980,fatty acid biosynthesis transcriptional regula...,
4,-6,EJ357_RS13985,ACP S-malonyltransferase,
5,-5,EJ357_RS13990,ketoacyl-ACP synthase III,
6,-4,EJ357_RS13995,acyl carrier protein,
7,-3,EJ357_RS14000,beta-ketoacyl-ACP synthase II,
8,-2,EJ357_RS14005,DUF3145 domain-containing protein,
9,-1,EJ357_RS14010,SGNH/GDSL hydrolase family protein,
10,0,EJ357_RS14015,aldose epimerase family protein,SCO2407
11,1,EJ357_RS14020,beta-glucosidase family protein,
12,2,EJ357_RS14030,RidA family protein,
13,3,EJ357_RS14035,LysR family transcriptional regulator,
14,4,EJ357_RS14040,C15 family peptidase,
15,5,EJ357_RS14050,EI24 domain-containing protein,
16,6,EJ357_RS14055,hypothetical protein,
17,7,EJ357_RS14060,M14 family zinc carboxypeptidase,
18,8,EJ357_RS14065,serine hydrolase domain-containing protein,
19,9,EJ357_RS14070,organic hydroperoxide resistance protein,
20,10,EJ357_RS14075,NADP-dependent oxidoreductase,

Streptomyces_vilmorinianum  FDM97_RS19630  (nearest: SCO2439:FDM97_RS20105, 90.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,FDM97_RS19570,ATP-binding protein,
1,-9,FDM97_RS19580,bifunctional salicylyl-CoA 5-hydroxylase/oxido...,
2,-8,FDM97_RS19585,carbon-nitrogen hydrolase family protein,
3,-7,FDM97_RS19590,cupin domain-containing protein,
4,-6,FDM97_RS19595,fumarylacetoacetate hydrolase family protein,
5,-5,FDM97_RS19600,maleate cis-trans isomerase family protein,
6,-4,FDM97_RS19605,PaaX family transcriptional regulator,
7,-3,FDM97_RS19610,hypothetical protein,
8,-2,FDM97_RS19620,YbhB/YbcL family Raf kinase inhibitor-like pro...,
9,-1,FDM97_RS19625,nucleoside-triphosphatase,
10,0,FDM97_RS19630,aldose epimerase family protein,SCO2407
11,1,FDM97_RS19635,alpha-L-arabinofuranosidase C-terminal domain-...,
12,2,FDM97_RS19640,glycoside hydrolase family 43 protein,
13,3,FDM97_RS19645,immunoglobulin-like domain-containing protein,
14,4,FDM97_RS19650,patatin-like phospholipase family protein,
15,5,FDM97_RS19655,hypothetical protein,
16,6,FDM97_RS19660,hypothetical protein,
17,7,FDM97_RS19665,acetoacetate decarboxylase family protein,
18,8,FDM97_RS19670,alpha/beta hydrolase,
19,9,FDM97_RS19675,metallophosphoesterase family protein,
20,10,FDM97_RS19680,GMC oxidoreductase,

Streptomyces_phytohabitans  ABXR15_RS17595  (nearest: SCO2401:ABXR15_RS20350, 534.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,ABXR15_RS17545,extracellular solute-binding protein,
1,-9,ABXR15_RS17550,carbohydrate ABC transporter permease,
2,-8,ABXR15_RS17555,carbohydrate ABC transporter permease,
3,-7,ABXR15_RS17560,beta-N-acetylhexosaminidase,
4,-6,ABXR15_RS17565,FAD binding domain-containing protein,
5,-5,ABXR15_RS17570,2Fe-2S iron-sulfur cluster-binding protein,
6,-4,ABXR15_RS17575,xanthine dehydrogenase family protein molybdop...,
7,-3,ABXR15_RS17580,hypothetical protein,
8,-2,ABXR15_RS17585,hypothetical protein,
9,-1,ABXR15_RS17590,hypothetical protein,
10,0,ABXR15_RS17595,aldose epimerase family protein,SCO2407
11,1,ABXR15_RS17600,CatB-related O-acetyltransferase,
12,2,ABXR15_RS17605,FG-GAP and VCBS repeat-containing protein,
13,3,ABXR15_RS17610,MFS transporter,
14,4,ABXR15_RS17615,LysR family transcriptional regulator,
15,5,ABXR15_RS17620,cysteine dioxygenase family protein,
16,6,ABXR15_RS17625,YeiH family protein,
17,7,ABXR15_RS17630,DEAD/DEAH box helicase,
18,8,ABXR15_RS17635,IclR family transcriptional regulator,
19,9,ABXR15_RS17640,S16 family serine protease,
20,10,ABXR15_RS17645,FAD-binding oxidoreductase,

Streptomyces_poriferorum  P8A21_RS38345  (nearest: SCO2401:P8A21_RS34285, 795.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,P8A21_RS38290,SRPBCC family protein,
1,-9,P8A21_RS38295,radical SAM protein,
2,-8,P8A21_RS38300,LysR family transcriptional regulator,
3,-7,P8A21_RS38305,oxidoreductase,
4,-6,P8A21_RS38315,GH25 family lysozyme,
5,-5,P8A21_RS38320,MarR family winged helix-turn-helix transcript...,
6,-4,P8A21_RS38325,hypothetical protein,
7,-3,P8A21_RS38330,multiple monosaccharide ABC transporter substr...,
8,-2,P8A21_RS38335,multiple monosaccharide ABC transporter ATP-bi...,
9,-1,P8A21_RS38340,multiple monosaccharide ABC transporter permease,
10,0,P8A21_RS38345,aldose epimerase family protein,SCO2407
11,1,P8A21_RS38350,carboxylesterase/lipase family protein,
12,2,P8A21_RS38355,S1 family peptidase,
13,3,P8A21_RS38360,"UDP-N-acetylmuramoyl-L-alanyl-D-glutamate--2, ...",
14,4,P8A21_RS38365,GNAT family N-acetyltransferase,
15,5,P8A21_RS38370,DUF2087 domain-containing protein,
16,6,P8A21_RS38375,DUF6630 family protein,
17,7,P8A21_RS38380,sigma-70 family RNA polymerase sigma factor,
18,8,P8A21_RS38385,LLM class F420-dependent oxidoreductase,
19,9,P8A21_RS38395,aldo/keto reductase,
20,10,P8A21_RS38400,DNA-binding response regulator,

Streptomyces_paludis  DVK44_RS35315  (nearest: SCO2440:DVK44_RS30615, 922.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,DVK44_RS35265,hypothetical protein,
1,-9,DVK44_RS35270,carbohydrate ABC transporter permease,
2,-8,DVK44_RS35275,carbohydrate ABC transporter permease,
3,-7,DVK44_RS35280,ABC transporter substrate-binding protein,
4,-6,DVK44_RS35285,cupin domain-containing protein,
5,-5,DVK44_RS35290,DUF6807 domain-containing protein,
6,-4,DVK44_RS35295,Gfo/Idh/MocA family protein,
7,-3,DVK44_RS35300,LacI family DNA-binding transcriptional regulator,
8,-2,DVK44_RS35305,Gfo/Idh/MocA family protein,
9,-1,DVK44_RS35310,alpha-L-arabinofuranosidase C-terminal domain-...,
10,0,DVK44_RS35315,aldose epimerase family protein,SCO2407
11,1,DVK44_RS35325,"3-carboxy-cis,cis-muconate cycloisomerase",
12,2,DVK44_RS35330,"protocatechuate 3,4-dioxygenase subunit alpha",
13,3,DVK44_RS35335,"protocatechuate 3,4-dioxygenase subunit beta",
14,4,DVK44_RS35340,thiolase family protein,
15,5,DVK44_RS35345,CoA transferase subunit B,
16,6,DVK44_RS35350,CoA transferase subunit A,
17,7,DVK44_RS35355,MarR family winged helix-turn-helix transcript...,
18,8,DVK44_RS35360,glycosyltransferase family 4 protein,
19,9,DVK44_RS35365,transferase,
20,10,DVK44_RS35370,oxygenase MpaB family protein,

Streptomyces_xiamenensis  SXIM_RS01350  (nearest: SCO2401:SXIM_RS06610, 1021.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,SXIM_RS01295,dipeptidase,
1,-9,SXIM_RS28465,FAD/NAD(P)-binding protein,
2,-8,SXIM_RS01310,asparagine synthase-related protein,
3,-7,SXIM_RS28780,lasso RiPP family leader peptide-containing pr...,
4,-6,SXIM_RS01320,LacI family DNA-binding transcriptional regulator,
5,-5,SXIM_RS01325,Gfo/Idh/MocA family protein,
6,-4,SXIM_RS01330,CynX/NimT family MFS transporter,
7,-3,SXIM_RS01335,FadR/GntR family transcriptional regulator,
8,-2,SXIM_RS01340,MFS transporter,
9,-1,SXIM_RS01345,hypothetical protein,
10,0,SXIM_RS01350,aldose epimerase family protein,SCO2407
11,1,SXIM_RS01355,response regulator transcription factor,
12,2,SXIM_RS01360,sensor histidine kinase,
13,3,SXIM_RS01365,hypothetical protein,
14,4,SXIM_RS01370,ABC transporter ATP-binding protein,
15,5,SXIM_RS01375,hypothetical protein,
16,6,SXIM_RS27890,hypothetical protein,
17,7,SXIM_RS27895,hypothetical protein,
18,8,SXIM_RS01385,VOC family protein,
19,9,SXIM_RS01390,NAD(P)-dependent oxidoreductase,
20,10,SXIM_RS01395,MerR family transcriptional regulator,

Streptomyces_boninensis  ACNNMR_RS34500  (nearest: SCO2403:ACNNMR_RS23280, 2188.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,ACNNMR_RS34445,FGGY family carbohydrate kinase,
1,-9,ACNNMR_RS34450,sugar ABC transporter permease,
2,-8,ACNNMR_RS34455,ATP-binding cassette domain-containing protein,
3,-7,ACNNMR_RS34460,sugar ABC transporter substrate-binding protein,
4,-6,ACNNMR_RS34465,DeoR/GlpR family DNA-binding transcription reg...,
5,-5,ACNNMR_RS34475,S1 family peptidase,
6,-4,ACNNMR_RS34480,carbohydrate ABC transporter permease,
7,-3,ACNNMR_RS34485,carbohydrate ABC transporter permease,
8,-2,ACNNMR_RS34490,extracellular solute-binding protein,
9,-1,ACNNMR_RS34495,alpha-N-arabinofuranosidase,
10,0,ACNNMR_RS34500,aldose epimerase family protein,SCO2407
11,1,ACNNMR_RS34505,glycerophosphodiester phosphodiesterase,
12,2,ACNNMR_RS34510,alpha-L-arabinofuranosidase C-terminal domain-...,
13,3,ACNNMR_RS34515,serine hydrolase domain-containing protein,
14,4,ACNNMR_RS34520,catalase/peroxidase HPI,
15,5,ACNNMR_RS34525,ROK family protein,
16,6,ACNNMR_RS34530,sugar ABC transporter ATP-binding protein,
17,7,ACNNMR_RS34535,ABC transporter permease,
18,8,ACNNMR_RS34540,ABC transporter permease,
19,9,ACNNMR_RS34545,substrate-binding domain-containing protein,
20,10,ACNNMR_RS34550,sugar phosphate isomerase/epimerase family pro...,

Streptomyces_bathyalis  G4Z16_RS02255  (nearest: SCO2440:G4Z16_RS24380, 4331.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,G4Z16_RS02205,RNA polymerase sigma factor,
1,-9,G4Z16_RS02210,hypothetical protein,
2,-8,G4Z16_RS02215,DUF5987 family protein,
3,-7,G4Z16_RS02220,GMC family oxidoreductase N-terminal domain-co...,
4,-6,G4Z16_RS02225,aminoglycoside adenylyltransferase domain-cont...,
5,-5,G4Z16_RS02230,GntR family transcriptional regulator,
6,-4,G4Z16_RS02235,ABC transporter ATP-binding protein,
7,-3,G4Z16_RS02240,hypothetical protein,
8,-2,G4Z16_RS02245,glycosyltransferase 87 family protein,
9,-1,G4Z16_RS02250,hypothetical protein,
10,0,G4Z16_RS02255,aldose epimerase family protein,SCO2407
11,1,G4Z16_RS02260,alpha/beta fold hydrolase,
12,2,G4Z16_RS02265,CehA/McbA family metallohydrolase,
13,3,G4Z16_RS02270,DNA alkylation repair protein,
14,4,G4Z16_RS02275,glycosyltransferase,
15,5,G4Z16_RS02280,RNA polymerase recycling motor ATPase HelR,
16,6,G4Z16_RS02285,RNA polymerase sigma factor,
17,7,G4Z16_RS02290,YciI family protein,
18,8,G4Z16_RS02295,hypothetical protein,
19,9,G4Z16_RS02300,diiron oxygenase,
20,10,G4Z16_RS02305,acyl carrier protein,

Streptomyces_kanamyceticus  CP970_RS30000  (nearest: SCO2403:CP970_RS06475, 4574.0 genes away)

    offset      locus_tag                                 description  rbh_hit
0      -10  CP970_RS29945              EI24 domain-containing protein
1       -9  CP970_RS29950     pyroglutamyl-peptidase I family protein
2       -8  CP970_RS29955                        hypothetical protein
3       -7  CP970_RS29960  TetR/AcrR family transcriptional regulator
4       -6  CP970_RS29965                     LysE family transporter
5       -5  CP970_RS45835                          phosphotransferase
6       -4  CP970_RS29980             NAD(P)-dependent oxidoreductase
7       -3  CP970_RS29985                         RidA family protein
8       -2  CP970_RS29990  TetR/AcrR family transcriptional regulator
9       -1  CP970_RS29995        glycoside hydrolase family 3 protein
10       0  CP970_RS30000             aldose epimerase family protein  SCO2407
11       1  CP970_RS30005          SGNH/GDSL hydrolase family protein
12       2  CP970_RS30010           DUF3145 domain-containing protein
13       3  CP970_RS30015               beta-ketoacyl-ACP synthase II
14       4  CP970_RS30020                        acyl carrier protein
15       5  CP970_RS30025                   ketoacyl-ACP synthase III
16       6  CP970_RS30030                    ACP S-malonyltransferase
17       7  CP970_RS30035       PucR family transcriptional regulator
18       8  CP970_RS30040                        pirin family protein
19       9  CP970_RS30045  serine hydrolase domain-containing protein
20      10  CP970_RS30050             GNAT family N-acetyltransferase

Streptomyces_hebeiensis  ACU6P3_RS00270  (nearest: SCO2403:ACU6P3_RS29140, 5509.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,ACU6P3_RS00220,hypothetical protein,
1,-9,ACU6P3_RS00225,NAD-dependent malic enzyme,
2,-8,ACU6P3_RS00230,AEC family transporter,
3,-7,ACU6P3_RS00235,hypothetical protein,
4,-6,ACU6P3_RS00240,glycine betaine/L-proline transporter ProP,
5,-5,ACU6P3_RS00245,Lrp/AsnC family transcriptional regulator,
6,-4,ACU6P3_RS00250,AbgT family transporter,
7,-3,ACU6P3_RS00255,M20 family metallopeptidase,
8,-2,ACU6P3_RS00260,hypothetical protein,
9,-1,ACU6P3_RS00265,SigE family RNA polymerase sigma factor,
10,0,ACU6P3_RS00270,aldose epimerase family protein,SCO2407
11,1,ACU6P3_RS00275,alpha-L-arabinofuranosidase C-terminal domain-...,
12,2,ACU6P3_RS00280,Gfo/Idh/MocA family protein,
13,3,ACU6P3_RS00285,LacI family DNA-binding transcriptional regulator,
14,4,ACU6P3_RS00290,ABC transporter substrate-binding protein,
15,5,ACU6P3_RS00295,carbohydrate ABC transporter permease,
16,6,ACU6P3_RS00300,carbohydrate ABC transporter permease,
17,7,ACU6P3_RS00305,hypothetical protein,
18,8,ACU6P3_RS00310,glycoside hydrolase family 3 C-terminal domain...,
19,9,ACU6P3_RS00315,extracellular solute-binding protein,
20,10,ACU6P3_RS00320,ABC transporter permease,

Streptomyces_griseofuscus  HEP81_RS26590  (nearest: None, nan genes away)

,offset,locus_tag,description,rbh_hit
0,-10,HEP81_RS26545,EstA family serine hydrolase,
1,-9,HEP81_RS26550,NADP-dependent oxidoreductase,
2,-8,HEP81_RS26555,MarR family winged helix-turn-helix transcript...,
3,-7,HEP81_RS26560,EI24 domain-containing protein,
4,-6,HEP81_RS26565,hypothetical protein,
5,-5,HEP81_RS42195,hypothetical protein,
6,-4,HEP81_RS26570,GlxA family transcriptional regulator,
7,-3,HEP81_RS26575,cysteine hydrolase family protein,
8,-2,HEP81_RS26580,cysteine hydrolase family protein,
9,-1,HEP81_RS26585,hypothetical protein,
10,0,HEP81_RS26590,aldose epimerase family protein,SCO2407
11,1,HEP81_RS26595,SRPBCC family protein,
12,2,HEP81_RS26600,SGNH/GDSL hydrolase family protein,
13,3,HEP81_RS26605,DUF3145 domain-containing protein,
14,4,HEP81_RS26610,beta-ketoacyl-ACP synthase II,
15,5,HEP81_RS26615,acyl carrier protein,
16,6,HEP81_RS26620,ketoacyl-ACP synthase III,
17,7,HEP81_RS26625,ACP S-malonyltransferase,
18,8,HEP81_RS26630,PucR family transcriptional regulator,
19,9,HEP81_RS26635,pirin family protein,
20,10,HEP81_RS26640,serine/threonine-protein kinase,

Streptomyces_murinus  GO605_RS29930  (nearest: None, nan genes away)

,offset,locus_tag,description,rbh_hit
0,-10,GO605_RS29880,serine/threonine-protein kinase,
1,-9,GO605_RS29885,pirin family protein,
2,-8,GO605_RS29890,fatty acid biosynthesis transcriptional regula...,
3,-7,GO605_RS29895,ACP S-malonyltransferase,
4,-6,GO605_RS29900,ketoacyl-ACP synthase III,
5,-5,GO605_RS29905,acyl carrier protein,
6,-4,GO605_RS29910,beta-ketoacyl-ACP synthase II,
7,-3,GO605_RS29915,DUF3145 domain-containing protein,
8,-2,GO605_RS29920,SGNH/GDSL hydrolase family protein,
9,-1,GO605_RS29925,SRPBCC family protein,
10,0,GO605_RS29930,aldose epimerase family protein,SCO2407
11,1,GO605_RS29935,hypothetical protein,
12,2,GO605_RS29940,cysteine hydrolase family protein,
13,3,GO605_RS29945,cysteine hydrolase family protein,
14,4,GO605_RS29950,GlxA family transcriptional regulator,
15,5,GO605_RS29955,hypothetical protein,
16,6,GO605_RS29960,EI24 domain-containing protein,
17,7,GO605_RS29965,MarR family winged helix-turn-helix transcript...,
18,8,GO605_RS29970,NADP-dependent oxidoreductase,
19,9,GO605_RS29975,serine hydrolase domain-containing protein,
20,10,GO605_RS29980,SCO2400 family protein,

Streptomyces_nodosus  CP978_RS11535  (nearest: None, nan genes away)

,offset,locus_tag,description,rbh_hit
0,-10,CP978_RS11485,hypothetical protein,
1,-9,CP978_RS11490,serine hydrolase domain-containing protein,
2,-8,CP978_RS11495,pirin family protein,
3,-7,CP978_RS11500,PucR family transcriptional regulator,
4,-6,CP978_RS11505,ACP S-malonyltransferase,
5,-5,CP978_RS11510,ketoacyl-ACP synthase III,
6,-4,CP978_RS11515,acyl carrier protein,
7,-3,CP978_RS11520,beta-ketoacyl-ACP synthase II,
8,-2,CP978_RS11525,DUF3145 domain-containing protein,
9,-1,CP978_RS11530,SGNH/GDSL hydrolase family protein,
10,0,CP978_RS11535,aldose epimerase family protein,SCO2407
11,1,CP978_RS11540,beta-glucosidase family protein,
12,2,CP978_RS11545,NADP-dependent oxidoreductase,
13,3,CP978_RS11550,MarR family winged helix-turn-helix transcript...,
14,4,CP978_RS34830,SCO2400 family protein,
15,5,CP978_RS11565,pyridoxal phosphate-dependent aminotransferase,
16,6,CP978_RS11570,LysM peptidoglycan-binding domain-containing p...,
17,7,CP978_RS11575,beta-galactosidase,
18,8,CP978_RS11580,hypothetical protein,
19,9,CP978_RS11585,ATP-grasp domain-containing protein,
20,10,CP978_RS11590,acyl-CoA synthetase,

Streptomyces_tubercidicus  STRTU_RS24690  (nearest: None, nan genes away)

,offset,locus_tag,description,rbh_hit
0,-10,STRTU_RS24630,organic hydroperoxide resistance protein,
1,-9,STRTU_RS24635,hypothetical protein,
2,-8,STRTU_RS24640,LacI family DNA-binding transcriptional regulator,
3,-7,STRTU_RS24645,sugar ABC transporter ATP-binding protein,
4,-6,STRTU_RS24655,ribokinase,
5,-5,STRTU_RS35990,nitrilase-related carbon-nitrogen hydrolase,
6,-4,STRTU_RS24670,pyroglutamyl peptidase,
7,-3,STRTU_RS24675,TetR/AcrR family transcriptional regulator,
8,-2,STRTU_RS24680,beta-glucosidase family protein,
9,-1,STRTU_RS24685,DUF4097 family beta strand repeat-containing p...,
10,0,STRTU_RS24690,aldose epimerase family protein,SCO2407
11,1,STRTU_RS24695,SGNH/GDSL hydrolase family protein,
12,2,STRTU_RS24700,DUF3145 domain-containing protein,
13,3,STRTU_RS24705,NAD(P)-dependent oxidoreductase,
14,4,STRTU_RS24710,beta-ketoacyl-ACP synthase II,
15,5,STRTU_RS24715,acyl carrier protein,
16,6,STRTU_RS24720,ketoacyl-ACP synthase III,
17,7,STRTU_RS24725,ACP S-malonyltransferase,
18,8,STRTU_RS24730,PucR family transcriptional regulator,
19,9,STRTU_RS24735,pirin family protein,
20,10,STRTU_RS24740,serine hydrolase domain-containing protein,

### SCO2439

In [44]:
sco2439 = isolated_hits[isolated_hits.qseqid.isin(["SCO2439"])]
sco2439

,ref_group,genome,qseqid,locus_tag,other_group_hits,nearest_hit,genes_away
25,SCO,Streptomyces_niveus,SCO2439,OG275_RS01590,4,SCO2440:OG275_RS00925,127.0
26,SCO,Streptomyces_rosealbus,SCO2439,ACRAKG_RS14275,5,SCO2407:ACRAKG_RS06195,1585.0
27,SCO,Streptomyces_durmitorensis,SCO2439,M4V62_RS28785,5,SCO2407:M4V62_RS37490,1706.0
28,SCO,Streptomyces_boninensis,SCO2439,ACNNMR_RS12515,5,SCO2440:ACNNMR_RS23265,2080.0
29,SCO,Streptomyces_halobius,SCO2439,K9S39_RS40770,0,None,NaN

In [45]:
for hit in sco2439.itertuples():
    print(f"{hit.genome}  {hit.locus_tag}  (nearest: {hit.nearest_hit}, {hit.genes_away} genes away)")
    display(show_neighbourhood(hit.genome, hit.locus_tag))

Streptomyces_niveus  OG275_RS01590  (nearest: SCO2440:OG275_RS00925, 127.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,OG275_RS01540,hypothetical protein,
1,-9,OG275_RS01545,hypothetical protein,
2,-8,OG275_RS01550,cold-shock protein,
3,-7,OG275_RS01555,DEAD/DEAH box helicase,
4,-6,OG275_RS01560,SCO5918 family protein,
5,-5,OG275_RS01565,hypothetical protein,
6,-4,OG275_RS01570,endonuclease,
7,-3,OG275_RS01575,hypothetical protein,
8,-2,OG275_RS01580,SpoIIE family protein phosphatase,
9,-1,OG275_RS01585,DUF6351 family protein,
10,0,OG275_RS01590,SMP-30/gluconolactonase/LRE family protein,SCO2439
11,1,OG275_RS01595,ABC transporter ATP-binding protein,
12,2,OG275_RS01600,ABC transporter permease,
13,3,OG275_RS01605,ATP-binding cassette domain-containing protein,
14,4,OG275_RS01610,sensor histidine kinase,
15,5,OG275_RS01615,response regulator transcription factor,
16,6,OG275_RS01620,non-homologous end-joining DNA ligase,
17,7,OG275_RS01625,peptide-methionine (S)-S-oxide reductase MsrA,
18,8,OG275_RS01630,ArsR/SmtB family transcription factor,
19,9,OG275_RS01635,SDR family NAD(P)-dependent oxidoreductase,
20,10,OG275_RS01640,MFS transporter,

Streptomyces_rosealbus  ACRAKG_RS14275  (nearest: SCO2407:ACRAKG_RS06195, 1585.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,ACRAKG_RS14225,LysR family transcriptional regulator,
1,-9,ACRAKG_RS14230,DUF5713 family protein,
2,-8,ACRAKG_RS14235,pyroglutamyl-peptidase I family protein,
3,-7,ACRAKG_RS14240,EI24 domain-containing protein,
4,-6,ACRAKG_RS14245,M14 family zinc carboxypeptidase,
5,-5,ACRAKG_RS14250,serine hydrolase domain-containing protein,
6,-4,ACRAKG_RS14255,organic hydroperoxide resistance protein,
7,-3,ACRAKG_RS14260,NADP-dependent oxidoreductase,
8,-2,ACRAKG_RS14265,MarR family winged helix-turn-helix transcript...,
9,-1,ACRAKG_RS14270,SCO2400 family protein,
10,0,ACRAKG_RS14275,SMP-30/gluconolactonase/LRE family protein,SCO2439
11,1,ACRAKG_RS14280,PucR family transcriptional regulator,
12,2,ACRAKG_RS14285,hypothetical protein,
13,3,ACRAKG_RS14290,DUF3068 domain-containing protein,
14,4,ACRAKG_RS14295,glycosyltransferase family 4 protein,
15,5,ACRAKG_RS14300,class I SAM-dependent methyltransferase,
16,6,ACRAKG_RS14305,alpha-(1->3)-arabinofuranosyltransferase domai...,
17,7,ACRAKG_RS14310,condensation protein,
18,8,ACRAKG_RS14315,class I SAM-dependent methyltransferase,
19,9,ACRAKG_RS14320,hypothetical protein,
20,10,ACRAKG_RS14325,Trm112 family protein,

Streptomyces_durmitorensis  M4V62_RS28785  (nearest: SCO2407:M4V62_RS37490, 1706.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,M4V62_RS28725,FkbM family methyltransferase,
1,-9,M4V62_RS28730,Trm112 family protein,
2,-8,M4V62_RS28735,hypothetical protein,
3,-7,M4V62_RS28740,class I SAM-dependent methyltransferase,
4,-6,M4V62_RS28755,DUF3367 domain-containing protein,
5,-5,M4V62_RS28760,class I SAM-dependent methyltransferase,
6,-4,M4V62_RS28765,glycosyltransferase family 4 protein,
7,-3,M4V62_RS28770,DUF3068 domain-containing protein,
8,-2,M4V62_RS28775,hypothetical protein,
9,-1,M4V62_RS28780,helix-turn-helix domain-containing protein,
10,0,M4V62_RS28785,SMP-30/gluconolactonase/LRE family protein,SCO2439
11,1,M4V62_RS28790,SCO2400 family protein,
12,2,M4V62_RS28795,MarR family winged helix-turn-helix transcript...,
13,3,M4V62_RS28800,NADP-dependent oxidoreductase,
14,4,M4V62_RS28805,organic hydroperoxide resistance protein,
15,5,M4V62_RS28810,serine hydrolase domain-containing protein,
16,6,M4V62_RS28815,M14 family zinc carboxypeptidase,
17,7,M4V62_RS28820,EI24 domain-containing protein,
18,8,M4V62_RS28825,pyroglutamyl peptidase,
19,9,M4V62_RS28830,aminoglycoside phosphotransferase family protein,
20,10,M4V62_RS28835,abortive phage infection protein,

Streptomyces_boninensis  ACNNMR_RS12515  (nearest: SCO2440:ACNNMR_RS23265, 2080.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,ACNNMR_RS12465,DUF3145 domain-containing protein,
1,-9,ACNNMR_RS12470,GDSL-type esterase/lipase family protein,
2,-8,ACNNMR_RS12475,aldose epimerase family protein,
3,-7,ACNNMR_RS12480,glycoside hydrolase family 172 protein,
4,-6,ACNNMR_RS12485,GNAT family N-acetyltransferase,
5,-5,ACNNMR_RS12490,ATP-binding protein,
6,-4,ACNNMR_RS12495,organic hydroperoxide resistance protein,
7,-3,ACNNMR_RS12500,NADP-dependent oxidoreductase,
8,-2,ACNNMR_RS12505,MarR family winged helix-turn-helix transcript...,
9,-1,ACNNMR_RS12510,SpoIIE family protein phosphatase,
10,0,ACNNMR_RS12515,SMP-30/gluconolactonase/LRE family protein,SCO2439
11,1,ACNNMR_RS12520,helix-turn-helix domain-containing protein,
12,2,ACNNMR_RS12525,hypothetical protein,
13,3,ACNNMR_RS12530,DUF3068 domain-containing protein,
14,4,ACNNMR_RS12535,glycosyltransferase family 4 protein,
15,5,ACNNMR_RS12540,class I SAM-dependent methyltransferase,
16,6,ACNNMR_RS12545,alpha-(1->3)-arabinofuranosyltransferase domai...,
17,7,ACNNMR_RS12550,condensation protein,
18,8,ACNNMR_RS12555,methyltransferase domain-containing protein,
19,9,ACNNMR_RS12560,DMT family transporter,
20,10,ACNNMR_RS12565,Trm112 family protein,

Streptomyces_halobius  K9S39_RS40770  (nearest: None, nan genes away)

,offset,locus_tag,description,rbh_hit
0,-10,K9S39_RS40710,roadblock/LC7 domain-containing protein,
1,-9,K9S39_RS40715,ATP-binding protein,
2,-8,K9S39_RS40720,substrate-binding domain-containing protein,
3,-7,K9S39_RS40725,methyltransferase domain-containing protein,
4,-6,K9S39_RS40730,aminotransferase class V-fold PLP-dependent en...,
5,-5,K9S39_RS40735,ArsR/SmtB family transcription factor,
6,-4,K9S39_RS40740,SHOCT domain-containing protein,
7,-3,K9S39_RS40745,hypothetical protein,
8,-2,K9S39_RS40760,PepSY domain-containing protein,
9,-1,K9S39_RS40765,IclR family transcriptional regulator domain-c...,
10,0,K9S39_RS40770,SMP-30/gluconolactonase/LRE family protein,SCO2439
11,1,K9S39_RS40775,hypothetical protein,
12,2,K9S39_RS40780,universal stress protein,
13,3,K9S39_RS40785,FBP domain-containing protein,
14,4,K9S39_RS40790,DUF2470 domain-containing protein,
15,5,K9S39_RS40795,nitroreductase family deazaflavin-dependent ox...,
16,6,K9S39_RS40800,MarR family winged helix-turn-helix transcript...,
17,7,K9S39_RS40805,DUF4142 domain-containing protein,
18,8,K9S39_RS40810,PP2C family protein-serine/threonine phosphatase,
19,9,K9S39_RS40815,SMP-30/gluconolactonase/LRE family protein,
20,10,K9S39_RS40820,chitinase,

### VNZ araB and araD

In [46]:
vnz_ara = isolated_hits[isolated_hits.qseqid.isin(["vnz_33175-araB", "vnz_33185-araD"])]
vnz_ara

,ref_group,genome,qseqid,locus_tag,other_group_hits,nearest_hit,genes_away
57,VNZ,Streptomyces_erythrochromogenes,vnz_33175-araB,OHA91_RS05465,3,vnz_33180-araA:OHA91_RS05365,16.0
58,VNZ,Streptomyces_iranensis,vnz_33175-araB,RY074_RS00855,0,None,NaN
60,VNZ,Streptomyces_canus,vnz_33185-araD,OHT68_RS00520,3,vnz_33175-araB:OHT68_RS02535,356.0
61,VNZ,Streptomyces_ipomoeae,vnz_33185-araD,ACNJZD_RS24120,1,vnz_33170-lacI:ACNJZD_RS14055,1930.0

In [47]:
for hit in vnz_ara.itertuples():
    print(f"{hit.genome}  {hit.locus_tag}  (nearest: {hit.nearest_hit}, {hit.genes_away} genes away)")
    display(show_neighbourhood(hit.genome, hit.locus_tag))

Streptomyces_erythrochromogenes  OHA91_RS05465  (nearest: vnz_33180-araA:OHA91_RS05365, 16.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,OHA91_RS05395,hypothetical protein,
1,-9,OHA91_RS05400,ATP-binding protein,
2,-8,OHA91_RS05405,hypothetical protein,
3,-7,OHA91_RS05410,hypothetical protein,
4,-6,OHA91_RS05415,ROK family protein,
5,-5,OHA91_RS05420,xylulokinase,
6,-4,OHA91_RS05425,xylose isomerase,
7,-3,OHA91_RS05435,GH1 family beta-glucosidase,
8,-2,OHA91_RS05450,aldose epimerase family protein,
9,-1,OHA91_RS05455,hypothetical protein,
10,0,OHA91_RS05465,ribulokinase,vnz_33175-araB
11,1,OHA91_RS05470,LacI family DNA-binding transcriptional regulator,
12,2,OHA91_RS05475,multiple monosaccharide ABC transporter substr...,
13,3,OHA91_RS05480,multiple monosaccharide ABC transporter ATP-bi...,
14,4,OHA91_RS05485,multiple monosaccharide ABC transporter permease,
15,5,OHA91_RS05495,RICIN domain-containing protein,
16,6,OHA91_RS05500,sigma-70 family RNA polymerase sigma factor,
17,7,OHA91_RS05505,non-reducing end alpha-L-arabinofuranosidase f...,
18,8,OHA91_RS05510,expansin EXLX1 family cellulose-binding protein,
19,9,OHA91_RS05515,SigE family RNA polymerase sigma factor,
20,10,OHA91_RS05520,hypothetical protein,

Streptomyces_iranensis  RY074_RS00855  (nearest: None, nan genes away)

,offset,locus_tag,description,rbh_hit
0,-10,RY074_RS50075,acyl carrier protein,
1,-9,RY074_RS00800,cytochrome P450,
2,-8,RY074_RS00805,SDR family NAD(P)-dependent oxidoreductase,
3,-7,RY074_RS00810,hypothetical protein,
4,-6,RY074_RS00815,hypothetical protein,
5,-5,RY074_RS00820,transposase,
6,-4,RY074_RS00835,SRPBCC domain-containing protein,
7,-3,RY074_RS00840,IS701 family transposase,
8,-2,RY074_RS00845,beta-galactosidase,
9,-1,RY074_RS00850,L-ribulose-5-phosphate 4-epimerase,
10,0,RY074_RS00855,ribulokinase,vnz_33175-araB
11,1,RY074_RS00860,sugar phosphate isomerase/epimerase family pro...,
12,2,RY074_RS00865,sugar phosphate isomerase/epimerase family pro...,
13,3,RY074_RS00870,alpha/beta fold hydrolase,
14,4,RY074_RS00875,carbohydrate ABC transporter permease,
15,5,RY074_RS00880,carbohydrate ABC transporter permease,
16,6,RY074_RS00885,ABC transporter substrate-binding protein,
17,7,RY074_RS00890,ThuA domain-containing protein,
18,8,RY074_RS00895,zinc-dependent alcohol dehydrogenase,
19,9,RY074_RS00900,sugar phosphate isomerase/epimerase family pro...,
20,10,RY074_RS00905,helix-turn-helix domain-containing protein,

Streptomyces_canus  OHT68_RS00520  (nearest: vnz_33175-araB:OHT68_RS02535, 356.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,OHT68_RS00455,DUF6192 family protein,
1,-9,OHT68_RS00460,hypothetical protein,
2,-8,OHT68_RS00465,hypothetical protein,
3,-7,OHT68_RS00475,Type 1 glutamine amidotransferase-like domain-...,
4,-6,OHT68_RS00480,NF041680 family putative transposase,
5,-5,OHT68_RS00485,glutaredoxin domain-containing protein,
6,-4,OHT68_RS00490,alpha/beta fold hydrolase,
7,-3,OHT68_RS00500,NF041680 family putative transposase,
8,-2,OHT68_RS00505,transposase,
9,-1,OHT68_RS00510,hypothetical protein,
10,0,OHT68_RS00520,L-ribulose-5-phosphate 4-epimerase AraD,vnz_33185-araD
11,1,OHT68_RS00525,L-arabinose isomerase,
12,2,OHT68_RS00530,ribulokinase,
13,3,OHT68_RS00535,CBM35 domain-containing protein,
14,4,OHT68_RS00540,carbohydrate ABC transporter permease,
15,5,OHT68_RS00545,carbohydrate ABC transporter permease,
16,6,OHT68_RS00550,ABC transporter substrate-binding protein,
17,7,OHT68_RS00555,LacI family DNA-binding transcriptional regulator,
18,8,OHT68_RS00560,alpha-galactosidase,
19,9,OHT68_RS00565,NAD(P)H-binding protein,
20,10,OHT68_RS00570,hypothetical protein,

Streptomyces_ipomoeae  ACNJZD_RS24120  (nearest: vnz_33170-lacI:ACNJZD_RS14055, 1930.0 genes away)

,offset,locus_tag,description,rbh_hit
0,-10,ACNJZD_RS24060,cold-shock protein,
1,-9,ACNJZD_RS24065,MerR family transcriptional regulator,
2,-8,ACNJZD_RS24075,hypothetical protein,
3,-7,ACNJZD_RS24080,sigma-70 family RNA polymerase sigma factor,
4,-6,ACNJZD_RS24085,multicopper oxidase family protein,
5,-5,ACNJZD_RS24090,PA domain-containing protein,
6,-4,ACNJZD_RS24095,extracellular solute-binding protein,
7,-3,ACNJZD_RS24100,carbohydrate ABC transporter permease,
8,-2,ACNJZD_RS24105,IS200/IS605 family transposase,
9,-1,ACNJZD_RS24110,RNA-guided endonuclease InsQ/TnpB family protein,
10,0,ACNJZD_RS24120,L-ribulose-5-phosphate 4-epimerase AraD,vnz_33185-araD
11,1,ACNJZD_RS24125,hypothetical protein,
12,2,ACNJZD_RS24130,hypothetical protein,
13,3,ACNJZD_RS24135,glycine betaine ABC transporter substrate-bind...,
14,4,ACNJZD_RS24140,hypothetical protein,
15,5,ACNJZD_RS24145,ATP-binding cassette domain-containing protein,
16,6,ACNJZD_RS24150,ABC transporter permease,
17,7,ACNJZD_RS24155,ATP-binding protein,
18,8,ACNJZD_RS24160,phosphatase PAP2 family protein,
19,9,ACNJZD_RS24165,polysaccharide deacetylase family protein,
20,10,ACNJZD_RS24170,SGNH/GDSL hydrolase family protein,

# what can be removed
ACNJZD_RS24120 reason: the only protein in the pathway